name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
          pip install lxml==4.9.1
          pip install opencv-python==4.8.1.78
          pip install openslide-python==1.1.2
          pip install scikit-image==0.18.1
          pip install Shapely==1.7.1
          pip install sharepy==2.0.0
          pip install matplotlib==3.6.2
          pip install Pillow==9.3.0
          pip install tifffile==2022.10.10
          pip install mpmath==1.2.1
          pip install h5py
          pip install scikit-learn
          pip install openpyxl
          pip install pandasl 
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true